replicaCount: 1

image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

appMessage: "Cart Service Running 🛒"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

httpRoute:
  enabled: false

resources: {}

autoscaling:
  enabled: false

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
