apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-checkout
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: checkout
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["sh", "-c", "echo {{ .Values.appMessage }}; sleep 3600"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}

